### ISSUE TITLE
support vmodule for json logger?

### ISSUE THREAD

**Issue by grosser** [kubernetes/klog#203]
/kind feature

we have some noise in our logs that we'd like to get rid of, we tried vmodule, but ran into:
`Error: non-default logging format doesn't honor flag: vmodule`

so we'd need:
- json formatter should show package info
- json formatter should allow silencing some packages

coming here from https://github.com/kubernetes/kubernetes/issues/96314

**Comment by serathius** [comment]
Thanks for filing the issue.
Support for vmodule will be considered as part of https://github.com/kubernetes/kubernetes/issues/99270

**Comment by krmayankk** [comment]
@serathius is there any pending work here or is this already being worked on ? my team would like to help on some of these issues

**Comment by serathius** [comment]
I have marked it as `triage accepted` as there is an open proposal for klog flag changes https://github.com/kubernetes/kubernetes/issues/99270#issuecomment-864605988
In this proposal I stated JSON should support both `v` and `vmodule`, so I think the issue can be worked on.

As the issue doesn't have any assignee nor anyone volunteering on comments, noone is current working on it. I would only say that this issue is non trivial to implement, so it might progress slower than issues tagged as good first issue.

**Comment by serathius** [comment]
@krmayankk Please check out https://www.kubernetes.dev/docs/guide/first-contribution/#find-a-good-first-topic for intro into contributing

**Comment by pchan** [comment]
@serathius I am interested in working on this issue. As I understand from your proposal, this is one of the flags that needs to be supported while many of the rest will be deprecated.

**Comment by serathius** [comment]
cc @pohly

**Comment by pohly** [comment]
I looked into this. See https://github.com/pohly/zapr/commits/vmodule

My conclusion from that experiment was that the solution would be awkward because conceptually it is the zap core which checks for "enabled" and vmodule support would have to be added there instead of the zapr wrapper. But I doubt that zap would accept such a feature request because it is not clear that it is important enough.

To me, vmodule is a developer feature. It has a performance impact. @grosser: had you considered that downside when you filed this feature request? It sounds like you want to use vmodule in production.

A better solution might be to fix the log call sites (reduce verbosity in the source code) or switch to a log consumer that can filter out unwanted log messages.

**Comment by grosser** [comment]
I opened this request because I wanted to be able to silence some modules from kubernetes logs, no consideration to performance was made :)

**Comment by pohly** [comment]
Do you still think this feature would be useful?

**Comment by grosser** [comment]
yes, it's also part of https://github.com/kubernetes/kubernetes/issues/99270
in general making structured json better seems like the right direction to me

**Comment by serathius** [comment]
Two things:
* "better" doesn't nesesery means "having more features". This feature has pretty high performance overhead so still discussing if to keep it
* As for "JSON should supporting same set of features as klog", it doesn't mean that we plan to implement all features. This issue is mostly about deprecating features that doesn't make sense long term so that in result features are the same.

**Comment by pohly** [comment]
@serathius: Perhaps add a question mark to the title of https://github.com/kubernetes/kubernetes/issues/99270? Then people who find that issue will know immediately that the issue was about discussing that, not stating the end goal.

**Comment by pohly** [comment]
We decided against supporting this because there is no good way to add vmodule support on top of zap (see my attempt in https://github.com/go-logr/zapr/pull/44). It's also not clear how many people need JSON output at the same time as vmodule-based filtering.

/close
