### ISSUE TITLE
logcheck: Add check for valid keys and number of args for ErrorS/InfoS

### ISSUE THREAD

**Issue by adisky** [kubernetes/klog#219]
/kind feature

**Describe the solution you'd like**
For  `InfoS` add checks for
- No. of arguments to `InfoS` should be uneven  (msg +X * (key+value) = 1 + 2X = always uneven number)
- Argument on uneven index is always string (we should never pass a var or const as key)
- No non-ascii characters in keys

For `ErrorS` add checks for
- No. of arguments should be even (err+msg+ X*(key+value)= 2+2X= always even number)
- Argument on even index is always a string
- No non-ascii characters in keys

**Anything else you would like to add:**
Example error output for following usage.
klog.V(2).InfoS("Starting container in a pod", "containerID", containerID, pod)  `Invalid Number of arguments for InfoS`
klog.V(2).InfoS("Killing containers in a pod",  7,  containerID ) `Invalid value for key`

_originally posted by @serathius here https://github.com/kubernetes/kubernetes/issues/98975#issuecomment-792581955_

**Comment by mowangdk** [comment]
one question: @adisky 

```
klog.V(2).InfoS("Starting container in a pod", "containerID", containerID, pod) Invalid Number of arguments for InfoS
klog.V(2).InfoS("Killing containers in a pod", 7, containerID ) Invalid value for key
```

is this means the InfoS & ErrorS func should return error?

**Comment by serathius** [comment]
@mowangdk Returning error would be an alternative way to detect invalid calls, but it has some major calls:
* If logging call is invalid there is no good action to take: If log call call returns errors what should we do? 
  Try logging again? No, as this can also fail. 
  Maybe return error up the calls stack? No, as failure in logging is not important enough that it should impact business logic of application.
* Logging is meant to be an simple call, that is used frequently. With error returned, calling logs would make code much more complicated and add a lot of bloat.

Approach we took here is that if there is an issue in log arguments that prevents from writing logs, logging library should fallback to writing an simpler error log that should succeed. This log should inform user about an invalid log call. As a result invalid log calls cannot be detected during compilation, and require executing the program. 

This issue is meant to introduce a static analysis mechanism that will detect the errors in PRs without needing to run the program, making it safer and cheaper to run.

**Comment by mowangdk** [comment]
ok get, returning error in log function really a bit weird

**Comment by adisky** [comment]
@mowangdk It is about to add validation in the static tool like here https://github.com/kubernetes/klog/blob/master/hack/tools/logcheck/main.go#L86.
If you go over the linked issue https://github.com/kubernetes/kubernetes/issues/98975 you will understand why this is needed.

**Comment by mowangdk** [comment]
> @mowangdk It is about to add validation in the static tool like here https://github.com/kubernetes/klog/blob/master/hack/tools/logcheck/main.go#L86.
> If you go over the linked issue [kubernetes/kubernetes#98975](https://github.com/kubernetes/kubernetes/issues/98975) you will understand why this is needed.

ok，thx~

**Comment by mowangdk** [comment]
one more questions

how to check key's value(must be ascii) in static ast?

**Comment by adisky** [comment]
@mowangdk We need to extract the function arguments from the ast tree, 
`klog.V(2).InfoS("Killing containers in a pod", 7, containerID )`
The index[0] arg for InfoS is message, index[1] arg is key (All odd index are then keys), once we extract the keys we need to validate it is valid ascii or not.

**Comment by mowangdk** [comment]
@adisky Is it possible that this key is a variable？

**Comment by adisky** [comment]
Nope, keys cannot be variable.

**Comment by mowangdk** [comment]
ok i see , all keys in kubernetes are const. but no restrictions in the code?
