### ISSUE TITLE
go routine created on flush logs leaks

### ISSUE THREAD

**Issue by katexochen** [kubernetes/klog#282]
/kind bug

**What steps did you take and what happened:**
uber/goleak found a leaking goroutine during test run:
```
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 19 in state chan receive, with k8s.io/klog/v2.(*loggingT).flushDaemon on top of the stack:
goroutine 19 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x0)
	/home/katexochen/go/pkg/mod/k8s.io/klog/v2@v2.30.0/klog.go:1181 +0x8b
created by k8s.io/klog/v2.init.0
	/home/katexochen/go/pkg/mod/k8s.io/klog/v2@v2.30.0/klog.go:420 +0x1c5
]
```
Previous mentioned in #188.
#190 tried to fix this.
I'm opening a new issue since both are closed now but the problem still exists.

**Comment by astoycos** [comment]
I also saw this recently when debugging [#107372](https://github.com/kubernetes/kubernetes/issues/107372) 
```
        [Goroutine 21 in state chan receive, with k8s.io/klog/v2.(*loggingT).flushDaemon on top of the stack:
        goroutine 21 [chan receive]:
        k8s.io/klog/v2.(*loggingT).flushDaemon(0x0)
                /home/astoycos/go/src/github.com/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1283 +0x6a
        created by k8s.io/klog/v2.init.0
                /home/astoycos/go/src/github.com/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:420 +0xfb
Additionally, this additional Go-routine

**Comment by pohly** [comment]
Starting a goroutine in init looks really bad to me. This should be under the control of the user of the package. I recently fixed flushing in Kubernetes and had no idea that klog was also doing it internally :sad:

@dims do you think we can move that out of `init` into a separate function that explicitly needs to be called by those who want this? Strictly speaking, this is a user-visible change of behavior.

**Comment by pohly** [comment]
Perhaps there is a way to solve this without breaking users who currently expect automatic flushing. Flushing only does anything when createFiles is called, because that is the only place where syncBuffer is created:

https://github.com/kubernetes/klog/blob/e7e411501098c01958a92f02d7c3d0286725a3c4/klog.go#L1267-L1285

Without syncBuffer, there's nothing that needs to be flushed. In particular, SetOutput writes without buffering:
https://github.com/kubernetes/klog/blob/e7e411501098c01958a92f02d7c3d0286725a3c4/klog.go#L984-L994

That means that we can move the flush daemon startup from init into createFiles:
https://github.com/kubernetes/klog/blob/e7e411501098c01958a92f02d7c3d0286725a3c4/klog.go#L984-L994
https://github.com/kubernetes/klog/blob/e7e411501098c01958a92f02d7c3d0286725a3c4/klog.go#L1267-L1285

Of course it must only be started once.

An API for stopping and waiting for it to stop can be added as an API extension at the same time.

Anyone willing to prepare a PR?

/help-wanted

**Comment by pohly** [comment]
`go test` runs the existing tests, but I doubt that it covers flushing of data. Adding some unit tests for this would be good.
