### ISSUE TITLE
OpenTelemetry support

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/klog#356]
/kind feature

**Describe the solution you'd like**

Logs are helpful data attached to OpenTelemetry traces. klog could support that by adding the log messages to the current tracing span if it exist.

**Anything else you would like to add:**

There is a k/k KEP existing for the kubelet tracing part: https://github.com/kubernetes/enhancements/issues/2831

Refers to https://github.com/kubernetes/kubernetes/issues/113414

**Comment by pohly** [comment]
Is this meant to be used together with JSON or text output or instead of it?

**Comment by saschagrunert** [comment]
> Is this meant to be used together with JSON or text output or instead of it?

I'd assume that it works in parallel to them. For example if tracing is enabled, then we pass the text message to the tracer side by side to the other output(s).

**Comment by pohly** [comment]
Makes sense, in particular when the tracer doesn't record all log output.

An implementation of this will depend on [contextual logging](https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/3077-contextual-logging) because non-contextual calls (`klog.Info`, `klog.InfoS`) have no way of determining the call context and thus the current tracing span.

But contextual logging alone is not enough because those calls are also not passed a context. Whoever adds a span to the context would also have to install a logger for it which then would get picked up by contextual logging calls in that call chain. As https://github.com/sallyom/enhancements-1/blob/master/keps/sig-instrumentation/2831-kubelet-tracing/README.md describes how the code gets instrumented, it probably should get extended to also cover the logging aspect.

**Comment by saschagrunert** [comment]
> Makes sense, in particular when the tracer doesn't record all log output.
> 
> An implementation of this will depend on [contextual logging](https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/3077-contextual-logging) because non-contextual calls (`klog.Info`, `klog.InfoS`) have no way of determining the call context and thus the current tracing span.

Depends how we make it usable. If we have a [global tracer set](https://pkg.go.dev/go.opentelemetry.io/otel#GetTracerProvider), then we may create spans from that as well.

**Comment by dashpole** [comment]
> klog could support that by adding the log messages to the current tracing span if it exist.

An alternative, which I would prefer, would be to attach the trace ID and span ID to logs as part of the structured output (as [trace_id and span_id](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/logs#trace-context-in-legacy-formats)), which can then be used to link to/from traces.

> Depends how we make it usable. If we have a [global tracer set](https://pkg.go.dev/go.opentelemetry.io/otel#GetTracerProvider), then we may create spans from that as well.

You still need a context if you want to link to other spans.  The global tracerprovider just lets you export spans from anywhere.

Thus far, we (sig-instrumentation) haven't touched on the subject of log or metric correlation, but we probably should extend our [contributor guidelines](https://github.com/kubernetes/community/blob/a858ed2d6db36fcb8aea48e1cd0ba724eece33b7/contributors/devel/sig-instrumentation/instrumentation.md) add traceing guidelines + log and metric correlation guidelines for other components. @dgrisonnet @logicalhan

**Comment by pohly** [comment]
> An alternative, which I would prefer, would be to attach the trace ID and span ID to logs as part of the structured output (as [trace_id and span_id](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/logs#trace-context-in-legacy-formats)), which can then be used to link to/from traces.

So no logging through OpenTelemetry?

That already works. The code that adds trace and span ID then would have to look like this:
```
traceID, spanID := <generate IDs>
ctx := context.WithValue(ctx, ... trace ID...)
ctx := context.WithValue(ctx, ... span ID...)
logger := klog.FromContext(ctx)
logger = klog.LoggerWithValues(logger, "trace_id", traceID, "span_id", spanID /* Kubernetes guidelines are to not use underscores in keys, but  https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/logs#trace-context-in-legacy-formats explicitly asks for it */)
ctx := klog.NewContext(ctx, logger)
```

**Comment by dashpole** [comment]
> So no logging through OpenTelemetry?

OpenTelemetry is working on a set of logging libraries, but they are still a ways off (https://opentelemetry.io/docs/instrumentation/go/#status-and-releases).  We can discuss what the benefits would be of adopting it, but I'm not sure what the benefits would be.

I'm just saying we shouldn't add all logs as span events.  Logging is its own thing, and has well-defined ways to correlate with tracing that it is probably best we follow.

What I really want is for `logger := klog.FromContext(ctx)` to always give me a logger with trace ID and span ID attached, if they exist in the context.

**Comment by pohly** [comment]
> What I really want is for logger := klog.FromContext(ctx) to always give me a logger with trace ID and span ID attached, if they exist in the context.

There are two ways of doing this:
- teach `klog.FromContext` about trace and span IDs
- teach the code which adds these IDs how to add a logger with the values to the context (my proposal above)

The problems with extending `klog.FromContext` are:
- Some code might use `logr.FromContext` directly because it has no klog dependency. Then it will not log the IDs.
- A solution that works for arbitrary loggers would make retrieving a logger from the context more expensive because it must search for IDs and modify the logger.
- A special solutions for the two loggers typically used by Kubernetes can delay that by just remembering the context, then look up the IDs if (and only if) needed.

The future contextual logging API in Golang will add some more options, but that is just being implemented and will be experimental. I am not sure whether want to wait for it. It will support adding the current context to the logger when retrieving it.

**Comment by pohly** [comment]
We also have to consider whether it is acceptable to make klog depend on OpenTelemetry. If any code in klog is meant to retrieve these IDs, it will have to have such a dependency, right?

**Comment by pohly** [comment]
It should be possible to just configure klog to extract certain values by giving it the keys. Then it won't depend on OpenTelemetry. It may even be possible to move this all into go-logr and do it so that it works for all logger backends - let me try that out...

**Comment by dashpole** [comment]
As a note, otel's interfaces, including context, are kept separate from the rest of OTel's codebase.  As a result, it has [nearly no dependencies](https://github.com/open-telemetry/opentelemetry-go/blob/main/trace/go.mod).  But it is still a consideration.

**Comment by sallyom** [comment]
> What I really want is for `logger := klog.FromContext(ctx)` to always give me a logger with trace ID and span ID attached, if they exist in the context.

I agree adding span id, trace id to logs will be useful.
This is the example i've seen.   
```golang
func logWithContext(span oteltrace.Span) log.Fields {
	return log.Fields{
		"span_id":  span.SpanContext().SpanID().String(),
		"trace_id": span.SpanContext().TraceID().String(),
	}
}
log.WithFields(logWithContext(span)).Info("Counter", zap.String("response", msg))
```

**Comment by pohly** [comment]
I think the best solution is with this changed in logr: https://github.com/go-logr/logr/pull/158

Once that is merged, https://github.com/kubernetes/klog/pull/359 can also be merged.

**Comment by dashpole** [comment]
As a note, those won't work well with OpenTelemetry.  The context keys for span context and for baggage are not exported, so we would need to support accessor functions or something similar to be able to make use of context-based functionality

**Comment by dashpole** [comment]
I think it was a general discussion.

It might've been a reference to how OpenCensus works, which is that all attributes ("tags" in OC) on spans/metrics are from context.  [Example](https://github.com/census-instrumentation/opencensus-go/blob/master/examples/quickstart/stats.go#L138).

OpenTelemetry's [SpanContext](https://github.com/open-telemetry/opentelemetry-go/blob/c4333a96875d520325fbcddc80c23be79674f297/trace/trace.go#LL205C13-L205C13) provides accessors for TraceID and SpanID (OpenTracing's SpanContext does not appear to provide explicit accessors).  I DO NOT think we should add all SpanContext-based k/v pairs from either [TraceState](https://github.com/open-telemetry/opentelemetry-go/blob/c4333a96875d520325fbcddc80c23be79674f297/trace/tracestate.go#L92) ([w3c tracestate](https://www.w3.org/TR/trace-context/#tracestate-header))or from [Baggage](https://github.com/open-telemetry/opentelemetry-go/blob/c4333a96875d520325fbcddc80c23be79674f297/propagation/baggage.go#L29) ([w3c baggage](https://www.w3.org/TR/baggage/)).  It would be nice if there was a way to opt-in values from baggage, though.

**Comment by pohly** [comment]
So if we log span ID and trace ID, what should that look like?
```
{"msg": "something", "tracing": {"spanID": "xyz", "traceID": "abc"}}
```

Or
```
{"msg": "something", "tracing.spanID": "xyz", "tracing.traceID": "abc"}
```

**Comment by dashpole** [comment]
It should look like:
```
{"msg": "something", "trace_id": "xyz", "span_id": "abc"}
```

See https://github.com/open-telemetry/opentelemetry-specification/tree/a87fb8c5a60f942d08c67c1582034eb8b4322009/specification/logs#trace-context-in-legacy-formats

**Comment by thockin** [comment]
> One possible alternative would be to allow passing a `func(ctx context.Context) interface{}` to the logger to retrieve some value

I want to be sensitive to performance , too - having to call an arbitrary number of functions once is not a big deal, but doing that on every log call seems unfortunate, unless we're clear about how we can cache those.

**Comment by pohly** [comment]
Logging as `"trace_id": "xyz", "span_id": "abc` in combination with a single function for lookup would be a good fit for something like `PseudoStruct` as discussed over in #357. We could do two functions, but I suspect that this is going to be less efficient and more complicated (need to supply the key names separately, multiple calls instead of one).

Calling `ctx.Value` through some function is adding some more overhead, but the baseline (`ctx.Value` itself, formatting of the log entry) is already pretty big, so relative to that it's probably not that much more.

@thockin I saw that you pre-render key/value pairs in structr's `WithValues` call. That makes sense if there are then multiple log calls that use that cached information, but it's probably worse for just a single call (need to store the cache somewhere) and definitely hurts when there is no log call at all.

When instrumenting the scheduler with contextual logging, a big concern was the slowdown at low log levels because those are typically used when performance is crucial. But I haven't checked how often there there would have been a `WithValues` call and no log call - I'll probably have to come back to it because [the PR](https://github.com/kubernetes/kubernetes/pull/111155) stalled.

Perhaps some on-demand caching could give us the best of both worlds (only do expensive work if needed, but then only once). It's just not easy to implement because such a cache would need to be shared between different `Logger` or `LogSink` instances.
